### ISSUE TITLE
Namespace Collector.LocalDatabase and Collector.Utilities are not found.

### ISSUE THREAD

**Issue by caideyi** [phspies/NetFlowCollector#1]
### NetFlowCollector/Collector/NetflowWorker.cs
**using Collector.LocalDatabase;
using Collector.Utilities;**

Hello, namespace **Collector.LocalDatabase** and **Collector.Utilities** are not found.
Are they referenced from other libraries?

**Comment by caideyi** [comment]
And lost Collector.Modules.Netflow.v10.**_V10Header_**

**Comment by alavitabar** [comment]
hi 
thanlk you for sharing this project
but 
using Collector.LocalDatabase;
using Collector.Utilities
not Exist!

**Comment by phspies** [comment]
This code was pulled from a larger project. Just remove the references as the code I uploaded does not use the classes.
